Feature/if2
mkenji0628/php_exercise01 pull request #6
Opened 2022-02-21 11:40 UTC by mkenji0628

5番以外完成

2022-02-21 12:00 UTC, mkenji0628 commented
4番が他のやり方がありそう・・・と思いながらです。

2022-02-21 12:52 UTC, kazu-taka requested changes
@mkenji0628 
コメントしたので確認お願いします😊

2022-02-21 12:52 UTC, kazu-taka commented on 05/if2_1.php
> +}
@mkenji0628 
課題に書いておりますが、この問題は`while`を使う問題となっているので、修正お願いします✨
<img width="848" alt="image" src="https://user-images.githubusercontent.com/5278718/154951749-80981000-0644-48f9-9743-98656a3f5ad5.png">

2022-02-21 12:52 UTC, kazu-taka commented on 05/if2_2.php
> +$m = $poket_money - $fund_raising;
@mkenji0628 
現在の所持金から101を引いている処理が2箇所にあります😊
1箇所で行う事が可能ですので、こちらは削除して下さい✨

2022-02-21 12:52 UTC, kazu-taka commented on 05/if2_2.php
> +    $m = $m - 101;
@mkenji0628 
残高を12行目で出力しているので、出力前に計算するのが良いと思います！
また、101は別の変数に代入されているので、変数の値を使用するようにして下さい✨

2022-02-21 12:52 UTC, kazu-taka commented on 05/if2_2.php
> +} while ($m > 0);
@mkenji0628 
残高を計算する処理を移動した場合、こちらの条件も変更になります✨

2022-02-21 12:52 UTC, kazu-taka commented on 05/if2_3.php
> +// print $key . '=>' . $value . '<br />'
@mkenji0628 
不要なコードは削除して下さい✨

2022-02-21 12:52 UTC, kazu-taka commented on 05/if2_4.php
> +        break;
@mkenji0628 
すみません！！！！
課題の内容が良くなったので変更しました:bow:
再度課題にチャレンジお願いします:bow:
https://github.com/elites-team/camp202202-php/blob/main/doc/06_php/exercise01/05_if2/01.md#4-switch%E6%96%87

2022-02-21 12:52 UTC, kazu-taka commented on 05/if2_5.php
> +// echo $subject;
@mkenji0628 
不要なコードは削除お願いします:bow:

2022-02-21 12:52 UTC, kazu-taka commented on 05/if2_5.php
> +            echo $subject . 'の試験は中止です。' . '<br>';
@mkenji0628 
間違いではないですが、「の試験は」と「です。」5回記述しているので、1回だけにすることも可能ですので、時間があったらチャレンジしてみて下さい✨

2022-02-21 13:33 UTC, mkenji0628 commented
#課題5の修正完了しました。

2022-02-21 23:39 UTC, kazu-taka requested changes
@mkenji0628 
コメントしたので確認お願いします😊

2022-02-21 23:39 UTC, kazu-taka commented on 05/if2_1.php
> +$m = $poket_money;
@mkenji0628 
所持金は`$poket_money`に代入されているので、`$m`にさらに代入せず、そのまま`$poket_money`を使うようにしてください✨

2022-02-21 23:39 UTC, kazu-taka commented on 05/if2_2.php
> +$m = $poket_money;
@mkenji0628 
こちらも`$m`は使用せずに、2つの変数だけで処理を行うようにして下さい✨
募金する処理の位置を変更する必要があります✨

2022-02-21 23:39 UTC, kazu-taka commented on 05/if2_5.php
> +$d = 'です。';
@mkenji0628 
上記の2文は特に変数にする必要はなく、switchが終わってからechoするように処理を変更し、そこのecho文に直接文字を入れるような感じにしてみて下さい✨

```php
// イメージなのでかなり簡単に書いてます
echo XXX の試験は YYY です
```

echo文で出力する時に必要な情報を変数に入れて保持して下さい😊

2022-02-25 07:28 UTC, noopy0415 commented
OKです✨
マージお願いします😊
![LGTM](https://cdn.lgtmoon.dev/images/87336)

2022-02-25 07:40 UTC, merged